name: Trigger Vercel Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_W9FX8V25V92oj89dVrzpEQPxbcsk/GXTfbkKwiT"
